dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng test:cover --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng e2e --protractor-config=./e2e/protractor-ci.conf.js

after_success:
  - npm run coveralls
